### ISSUE TITLE
Build error on Hassio

### ISSUE THREAD

**Issue by badaniels** [greylurk/hassio-custom-addons#1]
Hi,

I am trying to install your add-on to my hassio setup but it won't install. I searched into the log files, but I don't understand the error. Any help or guidance to get your add-on to work would be greatly appreciated.

Below is a dump of my log.

17-11-11 16:08:55 INFO (MainThread) [hassio.addons.addon] Create Home-Assistant addon data folder /data/addons/data/1deb755a_firetv
17-11-11 16:08:55 INFO (SyncWorker_15) [hassio.dock.addon] Start build 1deb755a/armhf-addon-firetv:0.0.2
17-11-11 16:08:55 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 323, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/util.py", line 31, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 474, in install
    if not await self.docker.install(self.last_version):
  File "/usr/lib/python3.6/site-packages/hassio/dock/util.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 219, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 232, in _build
    image = self.docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 175, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: Error parsing reference: "%%BASE_IMAGE%%" is not a valid repository/tag: invalid reference format

**Comment by dparker18** [comment]
I got this working by changing one line in the Dockerfile. See here:
https://home-assistant.io/blog/2017/09/26/new-hassio-build-system/
